name: event_bus_arch
description: This package is a part of Event-driven architecture providing sending, listening, processing and receiving the events.  
version: 2.0.6
repository: https://github.com/Avataromvatar/dart_event_bus
# publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # equatable: ^2.0.0
  # uuid: ^3.0.6
  intl: ^0.19.0
  async: ^2.11.0
  rxdart: ^0.27.7
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  