name: dart_event_bus
description: EventBus for Dart.   
version: 1.2.0
repository: https://github.com/Avataromvatar/dart_event_bus
publish_to: none
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  equatable: ^2.0.0
  uuid: ^3.0.6
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
