name: event_bus_arch
description: This package is a part of Event-driven architecture providing sending, listening, processing and receiving the events.  
version: 1.3.0+8
repository: https://github.com/Avataromvatar/dart_event_bus
# publish_to: none
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # equatable: ^2.0.0
  uuid: ^3.0.6
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  